### PR TITLE
ci: enable error detection

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#7985

### CODE REVIEW

**Comment by derekbit** [comment]
The error is due to https://github.com/longhorn/longhorn-spdk-engine/pull/110

**Comment by innobead** [comment]
the PR check failed.

**Comment by derekbit** [comment]
The CI test always failed.
https://drone-pr.longhorn.io/longhorn/longhorn-spdk-engine/134/1/3

@shuo-wu Can you help check it? Should we enable CI test for now?

**Comment by FrankYang0529** [comment]
Not sure why the `go vet` error doesn't break the pipeline first 🤔

```
Running: go vet
# github.com/longhorn/longhorn-spdk-engine/pkg/spdk
pkg/spdk/replica.go:523:14: result of fmt.Errorf call not used
```

**Comment by derekbit** [comment]
> Not sure why the `go vet` error doesn't break the pipeline first 🤔
> 
> ```
> Running: go vet
> # github.com/longhorn/longhorn-spdk-engine/pkg/spdk
> pkg/spdk/replica.go:523:14: result of fmt.Errorf call not used
> ```

Is it an error or warning?

**Comment by FrankYang0529** [comment]
> > Not sure why the `go vet` error doesn't break the pipeline first 🤔
> > ```
> > Running: go vet
> > # github.com/longhorn/longhorn-spdk-engine/pkg/spdk
> > pkg/spdk/replica.go:523:14: result of fmt.Errorf call not used
> > ```
> 
> Is it an error or warning?

I think it's error. We have to remove this line too.

https://github.com/longhorn/longhorn-spdk-engine/blob/dfb90ba8d693863da3ddae2adad5069ef401dcc0/scripts/validate#L7

**Review by innobead — COMMENTED** [review]
LGTM, but waiting for resolving the failed PR check.

**Pull request closed without merging**
