### PR TITLE
ci: simplify spdk_tgt start and stop

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue #

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by shuo-wu** [comment]
I prefer to launch a new tgt_target for each test case so that we can avoid some potential leftovers left by the previous tests.

**Comment by innobead** [comment]
Sounds good. Or before running each case, just cleaning up the potential leftover instances?

**Comment by derekbit** [comment]
> I prefer to launch a new tgt_target for each test case so that we can avoid some potential leftovers left by the previous tests.

Got it. The original method launching new tgt_target leads to random timeout error in both arm64 and amd64 platforms. I think it is due to something wrong in StartTarget function. We need to fix it first.

**Comment by innobead** [comment]
or we don't need to restart the target but rather use different resource names for each test so that they will be independent of each other. Although there would be a chance to have leftover instances from executed tests, the following tests will not be impacted.

**Pull request merged**
