### PR TITLE
test: fix test cases due to the change of namespaced Execute()

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#7939

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@derekbit will the change also break the 1.6 code which using ns executor?

**Comment by innobead** [comment]
@derekbit Please help fix the codespell err in another PR. Thanks.

**Comment by derekbit** [comment]
> @derekbit will the change also break the 1.6 code which using ns executor if we update the dependency in 1.6.

Not a breaking change. Just need to update the arguments.

**Comment by derekbit** [comment]
> @derekbit Please help fix the codespell err in another PR. Thanks.

The typo is due to
```
Error: ./proto/vendor/protobuf/src/google/protobuf/empty.proto:43: re-use ==> reuse
```

Do you mean fix the proto file or fix the codespell configuration?

**Pull request merged**
