### PR TITLE
Rename ptypes to spdkrpc

### PR DESCRIPTION
**Pull request by derekbit**
ptypes is used by longhorn-engine's syncagent grpc service

### CODE REVIEW

**Comment by shuo-wu** [comment]
`ptypes` means proto types. Do we need to have a different naming for each repo?

**Comment by derekbit** [comment]
> `ptypes` means proto types. Do we need to have a different naming for each repo?

Yes, we need a different for avoiding the proto.Register confilicts of legacy engine and spdk engine.

**Comment by shuo-wu** [comment]
Got it! I almost forgot that proto issue...

**Review by shuo-wu — APPROVED** [review]

**Comment by innobead** [comment]
`ptypes` pkg name is too general in longhorn-engine. For any gRPC naming should be more specific in the future.

**Pull request merged**
