### PR TITLE
Upgrade packages version

### PR DESCRIPTION
**Pull request by FrankYang0529**
* protoc: 24.3
* protoc-gen-go: 1.5.3
* google.golang.org/grpc: v1.58.1
* empty.proto: 24.3
* replace github.com/golang/protobuf with google.golang.org/protobuf

ref: https://github.com/longhorn/longhorn/issues/6666

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM.

I think we should unify the proto build in all repos. I feel the way in each repo seems slightly different.

**Comment by derekbit** [comment]
```
42.07 (16/16) Installing: libopenssl-devel-1.1.1l-150400.1.5.noarch [..done]
42.59 Refreshing service 'container-suseconnect-zypp'.
42.60 Loading repository data...
42.62 Reading installed packages...
42.69 Resolving package dependencies...
42.70 
42.70 The following 3 NEW packages are going to be installed:
42.70   libnuma-devel libnuma1 nasm
42.70 
42.70 The following 3 packages are not supported by their vendor:
42.70   libnuma-devel libnuma1 nasm
42.70 
42.70 3 new packages to install.
42.70 Overall download size: 466.4 KiB. Already cached: 0 B. After the operation, additional 3.1 MiB will be used.
42.70 Continue? [y/n/v/...? shows all options] (y): y
42.71 Retrieving: libnuma1-2.0.14.20.g4ee5e0c-150400.1.24.x86_64 (SLE_BCI) (1/3),  31.8 KiB    
42.71 Retrieving: libnuma1-2.0.14.20.g4ee5e0c-150400.1.24.x86_64.rpm [...done (31.8 KiB/s)]
43.71 Retrieving: nasm-2.15.05-150500.1.2.x86_64 (SLE_BCI) (2/3), 406.6 KiB    
43.71 Retrieving: nasm-2.15.05-150500.1.2.x86_64.rpm [.done]
43.73 Retrieving: libnuma-devel-2.0.14.20.g4ee5e0c-150400.1.24.x86_64 (SLE_BCI) (3/3),  28.0 KiB    
43.73 Retrieving: libnuma-devel-2.0.14.20.g4ee5e0c-150400.1.24.x86_64.rpm [.done]
43.74 
43.74 Checking for file conflicts: [..done]
43.75 (1/3) Installing: libnuma1-2.0.14.20.g4ee5e0c-150400.1.24.x86_64 [..done]
43.80 (2/3) Installing: nasm-2.15.05-150500.1.2.x86_64 [..done]
43.88 (3/3) Installing: libnuma-devel-2.0.14.20.g4ee5e0c-150400.1.24.x86_64 [..done]
44.38 Refreshing service 'container-suseconnect-zypp'.
44.39 Loading repository data...
44.42 Reading installed packages...
44.49 Resolving package dependencies...
44.50 
44.50 The following 7 NEW packages are going to be installed:
44.50   autoconf automake help2man libltdl7 libtool m4 perl-gettext
44.50 
44.50 The following 7 packages are not supported by their vendor:
44.50   autoconf automake help2man libltdl7 libtool m4 perl-gettext
44.50 
44.50 7 new packages to install.
44.50 Overall download size: 2.7 MiB. Already cached: 0 B. After the operation, additional 9.0 MiB will be used.
44.50 Continue? [y/n/v/...? shows all options] (y): y
44.50 Retrieving: libltdl7-2.4.6-3.4.1.x86_64 (SLE_BCI) (1/7),  32.6 KiB    
44.51 Retrieving: libltdl7-2.4.6-3.4.1.x86_64.rpm [...done (32.6 KiB/s)]
45.50 Retrieving: m4-1.4.18-4.3.1.x86_64 (SLE_BCI) (2/7), 199.7 KiB    
45.50 Retrieving: m4-1.4.18-4.3.1.x86_64.rpm [..done (32.0 KiB/s)]
46.48 Retrieving: perl-gettext-1.07-1.442.x86_64 (SLE_BCI) (3/7),  24.0 KiB    
46.48 Retrieving: perl-gettext-1.07-1.442.x86_64.rpm [.done]
46.49 Retrieving: autoconf-2.69-1.445.noarch (SLE_BCI) (4/7), 711.1 KiB    
46.49 Retrieving: autoconf-2.69-1.445.noarch.rpm [.done]
46.51 Retrieving: help2man-1.47.5-1.141.x86_64 (SLE_BCI) (5/7), 190.4 KiB    
46.51 Retrieving: help2man-1.47.5-1.141.x86_64.rpm [.done]
46.52 Retrieving: automake-1.15.1-4.10.2.noarch (SLE_BCI) (6/7), 817.9 KiB    
46.53 Retrieving: automake-1.15.1-4.10.2.noarch.rpm [.done]
46.54 Retrieving: libtool-2.4.6-3.4.1.x86_64 (SLE_BCI) (7/7), 748.2 KiB    
46.54 Retrieving: libtool-2.4.6-3.4.1.x86_64.rpm [.done]
46.55 
46.55 Checking for file conflicts: [..done]
46.58 (1/7) Installing: libltdl7-2.4.6-3.4.1.x86_64 [..done]
46.62 (2/7) Installing: m4-1.4.18-4.3.1.x86_64 [..done]
46.68 (3/7) Installing: perl-gettext-1.07-1.442.x86_64 [..done]
46.73 (4/7) Installing: autoconf-2.69-1.445.noarch [..done]
46.81 (5/7) Installing: help2man-1.47.5-1.141.x86_64 [..done]
46.88 (6/7) Installing: automake-1.15.1-4.10.2.noarch [..done]
46.97 (7/7) Installing: libtool-2.4.6-3.4.1.x86_64 [..done]
47.15 Using default SPDK env in /usr/src/spdk/lib/env_dpdk
47.15 Using default DPDK in /usr/src/spdk/dpdk/build
47.21 Configuring ISA-L (logfile: /usr/src/spdk/isa-l/spdk-isal.log)...done.
51.89 Configuring ISA-L-crypto (logfile: /usr/src/spdk/isa-l-crypto/spdk-isal-crypto.log)...done.
56.78 Creating mk/config.mk...done.
56.86 Creating mk/cc.flags.mk...done.
56.86 Type 'make' to build.
64.81 Traceback (most recent call last):
64.81   File "/usr/bin/meson", line 4, in <module>
64.81     from mesonbuild.mesonmain import main
64.81 ModuleNotFoundError: No module named 'mesonbuild'
64.82 make[1]: *** [Makefile:202: /usr/src/spdk/dpdk/build-tmp] Error 1
64.82 make: *** [/usr/src/spdk/mk/spdk.subdirs.mk:16: dpdkbuild] Error 2
64.82 make: *** Waiting for unfinished jobs....
------
Dockerfile.dapper1650068021:103
--------------------
 102 |     RUN echo "vm.nr_hugepages=$((HUGEMEM/2))" >> /etc/sysctl.conf
 103 | >>> RUN git clone https://github.com/longhorn/spdk.git ${SPDK_DIR} --recursive && \
 104 | >>>     if [ ${ARCH} == "amd64" ]; then \
 105 | >>>     cd ${SPDK_DIR} && \
 106 | >>>     git checkout ${SPDK_COMMIT_ID} && \
 107 | >>>     git submodule update --init && \
 108 | >>>     ./scripts/pkgdep.sh && \
 109 | >>>     ./configure --target-arch=nehalem --disable-tests --disable-unit-tests --disable-examples && \
 110 | >>>     make -j$(nproc) && \
 111 | >>>     make install; \
 112 | >>>     fi
 113 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/longhorn/spdk.git ${SPDK_DIR} --recursive &&     if [ ${ARCH} == \"amd64\" ]; then     cd ${SPDK_DIR} &&     git checkout ${SPDK_COMMIT_ID} &&     git submodule update --init &&     ./scripts/pkgdep.sh &&     ./configure --target-arch=nehalem --disable-tests --disable-unit-tests --disable-examples &&     make -j$(nproc) &&     make install;     fi" did not complete successfully: exit code: 2
FATA[0241] exit status 1                                
make: *** [Makefile:11: ci] Error 1
```

cc @shuo-wu @innobead

**Comment by innobead** [comment]
Good catch. The problem is caused by python311 symbolic links to python3 causing the python module import path messy between python3 and python311.

I knew @FrankYang0529 noticed python3 (3.6 reaching EOL), and it is noticed by Meson command, so he probably decided to use Python311; However, we still use zypper to install meson, but meson depends on the existing dependencies on 3.6. Thus, this caused the module to be unable to find when using python.

To fix this, use the default python3, even though it is EOL, but eventually, it will be updated over time. 

```console
f065b3a1a96a:/ # zypper info --requires meson
Refreshing service 'container-suseconnect-zypp'.
Loading repository data...
Reading installed packages...


Information for package meson:
------------------------------
Repository     : SLE_BCI
Name           : meson
Version        : 0.61.4-150500.1.7
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : unsupported
Installed Size : 7.4 MiB
Installed      : Yes
Status         : up-to-date
Source package : meson-0.61.4-150500.1.7.src
Upstream URL   : https://mesonbuild.com/
Summary        : Python-based build system
Description    : 
    Meson is a build system designed to optimise programmer productivity.
    It aims to do this by providing support for software development
    tools and practices, such as unit tests, coverage reports, Valgrind,
    CCache and the like. Supported languages include C, C++, Fortran,
    Java, Rust. Build definitions are written in a non-turing complete
    Domain Specific Language.
Requires       : [4]
    /usr/bin/python3
    python3-base
    python(abi) = 3.6
    ninja >= 1.7

```

**Comment by innobead** [comment]
That said, we should setup the CI check in this repo soon :slightly_smiling_face:  @shuo-wu

**Comment by innobead** [comment]
Just noticed that what @FrankYang0529 encountered was the builtin python 3.6 doesn't match the minimum requirement of grpcio 1.58. So, there are actually two issues, including Meson and grpcio requirements.

```bash
# python grpc-tools
RUN if [ "${ARCH}" == "s390x" ]; then \
    zypper -n in libopenssl-devel && \
    GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True pip3 install grpcio==1.58.0 grpcio_tools==1.58.0 protobuf==${PROTOBUF_VER_PY}; \
    else \
    pip3 install grpcio==1.58.0 grpcio_tools==1.58.0 protobuf==${PROTOBUF_VER_PY}; \
    fi
```

**Pull request merged**
