### PR TITLE
ci: change to use GitHub actions

### PR DESCRIPTION
**Pull request by FrankYang0529**
#### Which issue(s) this PR fixes:
https://github.com/longhorn/longhorn/issues/8039

### CODE REVIEW

**Comment by derekbit** [comment]
@FrankYang0529 

Can you help check

```

/home/runner/_work/_actions/codecov/codecov-action/v4/node_modules/@actions/io/lib/io.js:213
                    throw new Error(`Unable to locate executable file: ${tool}. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`);
^
Error: Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object.<anonymous> (/home/runner/_work/_actions/codecov/codecov-action/v4/node_modules/@actions/io/lib/io.js:213:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/_work/_actions/codecov/codecov-action/v4/node_modules/@actions/io/lib/io.js:24:1)
```

**Comment by FrankYang0529** [comment]
Hi @derekbit, I install `git` and resolve the error. However, there may have flaky test. I can't finish Build AMD64 binaries at the first try, but it pass at the second try.

* https://github.com/longhorn/longhorn-spdk-engine/actions/runs/9576741080/attempts/1
* https://github.com/longhorn/longhorn-spdk-engine/actions/runs/9576741080/attempts/2

For Build ARM64  binaries, test cases are always failed.

**Comment by derekbit** [comment]
> Hi @derekbit, I install `git` and resolve the error. However, there may have flaky test. I can't finish Build AMD64 binaries at the first try, but it pass at the second try.
> 
> * https://github.com/longhorn/longhorn-spdk-engine/actions/runs/9576741080/attempts/1
> * https://github.com/longhorn/longhorn-spdk-engine/actions/runs/9576741080/attempts/2
> 
> For Build ARM64 binaries, test cases are always failed.

Weird. No issues in the local environment.

**Comment by derekbit** [comment]
I might know the reason of the failure.

```
spdk_test.go:78:
    c.Assert(err, IsNil)
... value *errors.fundamental = timeout executing: /usr/bin/c [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net sh -c /usr/src/spdk/build/bin/spdk_tgt  --logflag all 2>&1 | tee /tmp/spdk_tgt.log] ("timeout executing: /usr/bin/nsenter [nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net sh -c /usr/src/spdk/build/bin/spdk_tgt  --logflag all 2>&1 | tee /tmp/spdk_tgt.log]")
```

spdk_tgt is running on foreground. If `nsenter...` cannot return within 60 seconds, it will error out.

**Comment by derekbit** [comment]
We can merge the PR. The ARM64 isn't related to the CI, and I will check it.

**Review by derekbit — APPROVED** [review]

**Pull request merged**
