### PR TITLE
Make the format of log messages consistent

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue #

#### What this PR does / why we need it:

Make the format of log messages consistent

### CODE REVIEW

**Review by innobead — CHANGES_REQUESTED** [review]
Suggest using gRPC errors exclusively within the gRPC server layer. For internal operations, let's continue using the usual error mechanism. This way will ensure clarity regarding when and where to use gRPC errors. WDYT?

**Comment by derekbit** [comment]
> Suggest using gRPC errors exclusively within the gRPC server layer. For internal operations, let's continue using the usual error mechanism. This way will ensure clarity regarding when and where to use gRPC errors. WDYT?

I thought the method before. There are many checks in the engine.go, replica.go and so on. The checks are related to different gRPC error codes, so using gRPC errors in server layer is not enough.

**Comment by innobead** [comment]
I see. Let's do this change first, but we should adopt the suggestion later, or the error handling code would become hard to maintain eventually.

**Comment by innobead** [comment]
Have a todo.

**Review by innobead — APPROVED** [review]

**Comment by derekbit** [comment]
Make it as a draft. Handle it in v1.7.0.

**Comment by innobead** [comment]
👍

**Comment by derekbit** [comment]
Handle this later.

**Pull request closed without merging**
